version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels: ["dependencies", "ci"]
    groups:
      gha-minor-and-patch:
        update-types: ["minor", "patch"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    labels: ["dependencies", "python"]
    versioning-strategy: "increase-if-necessary"
    groups:
      runtime-minor-and-patch:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      dev-minor-and-patch:
        dependency-type: "development"
        update-types: ["minor", "patch"]

  - package-ecosystem: "docker"
    directory: "/deploy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    commit-message:
      prefix: "deploy"
      include: "scope"
    labels: ["dependencies", "docker"]
