"""Golden-bytes parity for ``application/x-sfm-points-v1`` (lean-audit 5.3).

A small committed binary fixture (``fixtures/golden_points_v1.bin``) is
generated BY the server's canonical encoder
(:mod:`sfmapi.server.schemas.points_binary`) and re-generated + asserted
byte-identical on every run, so the checked-in bytes can never drift
from the encoder. The same fixture is then decoded through

  (a) the server's own decoder (``decode_records``), and
  (b) the generated Python SDK's ``parse_points_binary``
      (``sfmapi_client_gen._ergonomics``),

asserting identical decoded values against one hardcoded golden table.
The TypeScript SDK decodes the very same fixture file in
``sfmapi-sdk/typescript/test/golden_points.test.ts`` against the same
hardcoded table (kept in lockstep by hand — change one, change both).
C++ golden coverage is deferred until the cpp/ WIP lands (see CLAUDE.md).

The golden records intentionally cover edge values: an all-zeros record,
max uint8 colors + max uint16 track_len + max uint64 id, large exact-in-
float32 coordinates (powers of two), and floats whose float32 encodings
contain non-ASCII-safe bytes (0.1, -3.14159, 2.71828 — these also pin
the float32 rounding behavior across languages).
"""

from __future__ import annotations

import os
import struct

import pytest

from tests.contract.conftest import FIXTURE_DIR
from tests.contract.test_e_generated_ergonomics import _import_generated

pytestmark = pytest.mark.contract

GOLDEN_FIXTURE = FIXTURE_DIR / "golden_points_v1.bin"


def f32(x: float) -> float:
    """Round ``x`` through float32 — the wire precision of xyz/bbox."""
    return struct.unpack("<f", struct.pack("<f", x))[0]  # type: ignore[no-any-return]


# Keep in lockstep with GOLDEN in
# sfmapi-sdk/typescript/test/golden_points.test.ts.
GOLDEN_BBOX_MIN = (-16777216.0, -3.25, -0.5)
GOLDEN_BBOX_MAX = (1073741824.0, 65536.0, 2.75)
# (point3d_id, xyz, rgb, track_len)
GOLDEN_ROWS: list[tuple[int, tuple[float, float, float], tuple[int, int, int], int]] = [
    (0, (0.0, 0.0, 0.0), (0, 0, 0), 0),
    (0xFFFFFFFFFFFFFFFF, (1.5, -2.25, 0.125), (255, 255, 255), 65535),
    (42, (1073741824.0, -16777216.0, 65536.0), (0, 128, 255), 7),
    (0xDEADBEEF, (0.1, -3.14159, 2.71828), (1, 2, 3), 1234),
]


def _golden_bytes() -> bytes:
    """Encode the golden rows via the server's canonical encoder."""
    from sfmapi.server.schemas.points_binary import Point3DRecord, encode_all

    records = [
        Point3DRecord(point3d_id=pid, xyz=xyz, rgb=rgb, track_len=tl)
        for pid, xyz, rgb, tl in GOLDEN_ROWS
    ]
    return encode_all(records, bbox_min=GOLDEN_BBOX_MIN, bbox_max=GOLDEN_BBOX_MAX)


def test_golden_fixture_matches_encoder_bytes() -> None:
    """The committed fixture MUST be byte-identical to what the
    server encoder produces for the golden rows — the fixture can
    never drift from the encoder. A change to the wire format shows
    up here as a byte diff; bump the fixture (and the SDK golden
    tables) intentionally via ``TESTS_CONTRACT_REFRESH=true``, never
    by hand-editing bytes.
    """
    encoded = _golden_bytes()
    if not GOLDEN_FIXTURE.is_file() or os.environ.get("TESTS_CONTRACT_REFRESH"):
        GOLDEN_FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN_FIXTURE.write_bytes(encoded)
    on_disk = GOLDEN_FIXTURE.read_bytes()
    assert on_disk == encoded, (
        "fixtures/golden_points_v1.bin no longer matches the canonical "
        "encoder output — the points-v1 wire format changed. If "
        "intentional, regenerate with TESTS_CONTRACT_REFRESH=true and "
        "update the golden tables here and in "
        "sfmapi-sdk/typescript/test/golden_points.test.ts."
    )


def test_server_decoder_round_trips_golden_fixture() -> None:
    """Decode the fixture through the server's own decoder and check
    every field against the hardcoded golden table (float32-rounded).
    """
    from sfmapi.server.schemas.points_binary import decode_records

    records, bmin, bmax = decode_records(GOLDEN_FIXTURE.read_bytes())
    assert bmin == tuple(f32(v) for v in GOLDEN_BBOX_MIN)
    assert bmax == tuple(f32(v) for v in GOLDEN_BBOX_MAX)
    assert len(records) == len(GOLDEN_ROWS)
    for rec, (pid, xyz, rgb, tl) in zip(records, GOLDEN_ROWS, strict=True):
        assert rec.point3d_id == pid
        assert rec.xyz == tuple(f32(v) for v in xyz)
        assert rec.rgb == rgb
        assert rec.track_len == tl


def test_generated_sdk_decodes_golden_fixture_identically() -> None:
    """Decode the fixture through the generated Python SDK's
    ``parse_points_binary`` and assert the decoded values are
    identical to the server decoder's — field for field — plus equal
    to the hardcoded golden table. This is the Python leg of the
    cross-language golden-bytes parity guarantee (TS leg:
    ``golden_points.test.ts``).
    """
    from sfmapi.server.schemas.points_binary import decode_records

    erg, _ = _import_generated()
    data = GOLDEN_FIXTURE.read_bytes()

    srv_records, srv_bmin, srv_bmax = decode_records(data)
    sdk = erg.parse_points_binary(data)

    assert sdk.count == len(srv_records) == len(GOLDEN_ROWS)
    assert sdk.bbox_min == srv_bmin
    assert sdk.bbox_max == srv_bmax
    for sdk_rec, srv_rec, (pid, xyz, rgb, tl) in zip(
        sdk.records, srv_records, GOLDEN_ROWS, strict=True
    ):
        # SDK == server (parity)
        assert sdk_rec.point3d_id == srv_rec.point3d_id
        assert sdk_rec.xyz == srv_rec.xyz
        assert sdk_rec.rgb == srv_rec.rgb
        assert sdk_rec.track_len == srv_rec.track_len
        # both == golden table (anchors the TS hardcoded expectations)
        assert sdk_rec.point3d_id == pid
        assert sdk_rec.xyz == tuple(f32(v) for v in xyz)
        assert sdk_rec.rgb == rgb
        assert sdk_rec.track_len == tl
